name: 'Laravel Auto Deploy'

description: 'Deploy Laravel Application to Server via SSH by RSync'
author: 'karson'
branding:
    icon: 'send'
    color: 'green'

inputs:
    remote-user: 
        description: 'Deploy user'
        required: true
    remote-host: 
        description: 'Deploy host'
        required: true
    ssh-private-key: 
        description: 'SSH Private Key'
        required: true
    target-directory: 
        description: 'Path source on server'
        required: true
    ssh-port: 
        description: 'Deploy port'
        required: false
    owner: 
        description: 'Deploy owner'
        required: false
    commands: 
        description: 'Command to run after default artisan commands'
        required: false

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.remote-user }}
        - ${{ inputs.remote-host }}
        - ${{ inputs.ssh-private-key }}
        - ${{ inputs.target-directory }}
        - ${{ inputs.ssh-port }}
        - ${{ inputs.owner }}
        - ${{ inputs.commands }}
